# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - springserveur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read            # required for actions/checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn --batch-mode clean package

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write           # for OIDC login
      contents: read            # to pull the repo if needed

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Log in with federated credentials
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_D159609EE50D43E3A8C638B9AD1483F0 }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_DE043B8A5E1440EE9A57BFA69554785B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E775322E863747A3B05074D8559D716A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'springserveur'
          slot-name: 'Production'
          package: '${{ github.workspace }}/**/*.jar'   # ← added (explicit JAR path)
